Murray.OnlineStaffManager.Web/Controllers/EmployeeSicknessController.cs
using AutoMapper;
using Murray.OnlineStaffManager.Core;
using Murray.OnlineStaffManager.Core.Infrastructure;
using Murray.OnlineStaffManager.DAL.Repositories;
using Murray.OnlineStaffManager.DAL.Services;
using Murray.OnlineStaffManager.Models;
using Murray.OnlineStaffManager.Web.Models;
using Murray.OnlineStaffManager.Web.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
namespace Murray.OnlineStaffManager.Web.Controllers
{
    [Authorize]
    public class EmployeeSicknessController : BaseController
    {
        private IEmployeeSicknessService _employeeSicknessService;
        private IEmployeeService _employeeService;

        public EmployeeSicknessController(
            IEmployeeSicknessService employeeSicknessService,
            IEmployeeService employeeService,
            UserTable<AppMember> appMemberRepository,
            ICompanyRepository companyRepository)
            : base(appMemberRepository, companyRepository)
        {
            _employeeSicknessService = employeeSicknessService;
            _employeeService = employeeService;
        }

        public ActionResult Index()
        {
            //todo: add pagination logic
            var model = _employeeSicknessService.GetAll((Guid)Session["CompanyId"]);

            EmployeeSicknessListViewModel vm = new EmployeeSicknessListViewModel();

            foreach (var m in model)
            {
                // Historic
                if(m.SicknessEndDate < DateTime.Today)
                {
                    vm.Historic.Add(Mapper.Map<EmployeeSickness, EmployeeSicknessViewModel>(m));
                }
                // Current
                else
                {
                    vm.Current.Add(Mapper.Map<EmployeeSickness, EmployeeSicknessViewModel>(m));
                }
            }
            return View(vm);
        }

        public ActionResult Add()
        {
            // Get a list of all employees at the company 
            IEnumerable<Employee> employees = _employeeService.GetAll((Guid)Session["CompanyId"]);
            IEnumerable<SicknessType> sicknesses = _employeeSicknessService.GetAllSicknessTypes();

            EmployeeSicknessAddViewModel vm = new EmployeeSicknessAddViewModel();
            // Create a select list for employees
            foreach (var em in employees)
            {
                vm.EmployeeList.Add(new SelectListItem
                {
                    Text = em.FullName,
                    Value = em.Id.ToString()
                });
            }

            // Create a select list for sickness types
            foreach (var type in sicknesses)
            {
                vm.SicknessTypesList.Add(new SelectListItem
                {
                    Text = type.Description,
                    Value = type.Id.ToString()
                });
            }
            return View(vm);
        }

        public ActionResult AddSickness(EmployeeSicknessAddViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Add", model);
            }
            EmployeeSickness employeeSicknesses = 
                Mapper.Map<EmployeeSicknessAddViewModel, EmployeeSickness>
                  (model);

            // If the user has left the end date blank then null the value before persisting to db.
            if(model.SicknessEndDate == DateTime.MinValue)
            {
                employeeSicknesses.SicknessEndDate = null;
            }
            _employeeSicknessService.Add(employeeSicknesses);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(Guid EmployeeSicknessId)
        {
            EmployeeSicknessDetailViewModel employeeSickness =
                Mapper.Map<EmployeeSickness, EmployeeSicknessDetailViewModel>
                (_employeeSicknessService.Get(EmployeeSicknessId));

            IEnumerable<SicknessType> sicknessTypes = _employeeSicknessService.GetAllSicknessTypes();
            foreach (var type in sicknessTypes)
            {
                employeeSickness.SicknessTypesList.Add(new SelectListItem
                {
                    Text = type.Description,
                    Value = type.Id.ToString()
                });
            }

            return View(employeeSickness);
        }

        public ActionResult NewSicknessType()
        {
            return View();
        }

        public ActionResult AddNewSicknessType(SicknessTypeAddViewModel model)
        {
            _employeeSicknessService.AddSicknessType(new SicknessType
            {
                CompanyId = (Guid)Session["CompanyId"],
                Description = model.Description,
                IsActive = true
            });

            return RedirectToAction("Index");
        }

        public ActionResult DeleteSicknessType(Guid SicknessTypeId)
        {
            _employeeSicknessService.DeleteSicknessTypeById(SicknessTypeId);
            return RedirectToAction("Index");
        }
    }
}

Murray.OnlineStaffManager.Web/Controllers/SicknessTypeController.cs
using System.Web.Mvc;
using Murray.OnlineStaffManager.DAL.Services;
using Murray.OnlineStaffManager.Web.Models.ViewModels;
using System.Collections.Generic;
using Murray.OnlineStaffManager.Models;
using AutoMapper;
using Murray.OnlineStaffManager.Web.Models;
using Murray.OnlineStaffManager.Core;
using Murray.OnlineStaffManager.DAL.Repositories;
using Murray.OnlineStaffManager.Core.Infrastructure;

namespace Murray.OnlineStaffManager.Web.Controllers
{
    [Authorize]
    public class SicknessTypeController : BaseController
    {
        private IEmployeeSicknessService _employeeSicknessService;
        public SicknessTypeController(UserTable<AppMember> appMemberRepository,
                                      IEmployeeSicknessService employeeSicknessService,
                                      ICompanyRepository companyRepository) 
            : base(appMemberRepository, companyRepository)
        {
            _employeeSicknessService = employeeSicknessService;
        }

        // GET: SicknessType
        public ActionResult List()
        {
            var model = Mapper.Map<IEnumerable<SicknessType>, IEnumerable<SicknessTypesListViewModel>>
                (_employeeSicknessService.GetAllSicknessTypes());
            return PartialView("_SicknessTypes", model);
        }
    }
}

Murray.OnlineStaffManager.Web/Views/EmployeeSickness/Add.cshtml
@model Murray.OnlineStaffManager.Web.Models.ViewModels.EmployeeSicknessAddViewModel
@{
    ViewBag.Title = "Add Employee Sickness";
}
@using (Html.BeginForm("AddSickness", "EmployeeSickness", FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="well">
        <p>Add an employee sickness episode using the form below. Leave the end date blank if they have not returned to work yet.</p>
    </div>
    <hr />
    <div class="form-horizontal well">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group-lg">
            @Html.LabelFor(m => m.EmployeeList, new { @class = "control-label" })
            @Html.DropDownListFor(x => x.EmployeeId, new SelectList(Model.EmployeeList, "Value", "Text"), new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.EmployeeId, "", new { @class = "text-danger" })
        </div>
        <div class="form-group-lg">
            @Html.LabelFor(m => m.SicknessTypesList, new { @class = "control-label" })
            @Html.DropDownListFor(x => x.SicknessTypeId, new SelectList(Model.SicknessTypesList, "Value", "Text"), new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.SicknessTypeId, "", new { @class = "text-danger" })
        </div> 
        <div class="form-group-lg">
            @Html.LabelFor(m => m.SicknessStartDate, new { @class = "control-label" })
            <div class="input-group date">
                @Html.TextBoxFor(m => m.SicknessStartDate, new { @class = "form-control datepicker", @placeholder = "dd/mm/yyyy" })
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
            </div>
            @Html.ValidationMessageFor(m => m.SicknessStartDate, "", new { @class = "text-danger" })
        </div>
        <div class="form-group-lg">
            @Html.LabelFor(m => m.SicknessEndDate, new { @class = "control-label" })
            <div class="input-group date">
                @Html.TextBoxFor(m => m.SicknessEndDate, new { @class = "form-control datepicker", @placeholder = "dd/mm/yyyy" })
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
            </div>
            @Html.ValidationMessageFor(m => m.SicknessEndDate, "", new { @class = "text-danger" })
        </div>
        <div class="form-group-lg">
            @Html.Bootstrap().TextAreaFor(m=>m.Comments, 5)
        </div> 
        <div class="form-group-lg">
            <br />
            <button type="submit" class="btn btn-lg btn-success"><i class="fa fa-thermometer"></i> Add</button>
        </div>
    </div>
}
<script type="text/javascript">
    $(document).ready(function () {
        $('.input-group.date').datepicker({
            format: 'dd/mm/yyyy',
            orientation: 'bottom'
        });
    });
</script>

Murray.OnlineStaffManager.Web/Views/EmployeeSickness/Edit.cshtml
@model Murray.OnlineStaffManager.Web.Models.ViewModels.EmployeeSicknessDetailViewModel
@{
    ViewBag.Title = "Edit Employee Sickness";
    @Scripts.Render("~/bundles/auth", "~/bundles/utils")
}

@using (var form = Html.Bootstrap().Form("Edit", "EmployeeSickness", FormMethod.Post).Begin())
{
    @Html.AntiForgeryToken()
    <div class="well">
        <p>Review and make any changes below.</p>
    </div>
    <hr />

    <div class="well form-horizontal">
        @form.Input("Employee", "Employee", Model.Forename + " " + Model.Surname).AddAttribute("disabled", "disabled")

        @using (form.FormGroup("Sickness Start Date").Begin())
        {
            <div class="input-group date">
                <input id="SicknessStartDate" type="text" placeholder="dd/mm/yyyy" value="@Model.SicknessStartDate.ToString("dd/M/yyyy")" class="form-control"><span class="input-group-addon"><i class="fa fa-calendar"></i></span>
            </div>
        }

        @using (form.FormGroup("Sickness End Date").Begin())
        {
            <div class="input-group date">
                @if (Model.SicknessEndDate == null)
                {
                    <input id="SicknessEndDate" type="text" placeholder="dd/mm/yyyy" class="form-control"><span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                }
                else
                {
                    <input id="SicknessEndDate" type="text" placeholder="dd/mm/yyyy" value="@Model.SicknessEndDate.Value.ToString("dd/M/yyyy")" class="form-control"><span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                }
            </div>
        }

        @form.TextAreaFor(m => m.Comments, 5)
        @Html.Bootstrap().SelectFor(x => x.SicknessTypeId, new SelectList(Model.SicknessTypesList, "Value", "Text"))

        <div class="form-group-lg">
            <br />
            <button class="btn btn-success btn-lg" type="button" onclick="editEmployeeSickness()">
                <i class="fa fa-floppy-o"></i> Update
            </button>
        </div>
    </div>
}

<script type="text/javascript">
    var apiBase = getApiBase() + "api/";
    $(document).ready(function () {
        initDatePickers();
    });

    function editEmployeeSickness() {
        var entity = {
            "Id": @Html.Raw(Json.Encode(Model.Id)),
            "SicknessStartDate": parseDate($('#SicknessStartDate').val()),
            "SicknessEndDate": parseDate($('#SicknessEndDate').val()),
            "SicknessTypeId": $('#SicknessTypeId').val(),
            "Comments": $('#Comments').val()
        };

        $.ajax({
            url: apiBase + "Sickness/Put",
            dataType: "json",
            contentType: 'application/json; charset=utf-8',
            data: JSON.stringify(entity),
            headers: getTokenWithHeader(),
            type: "PUT",
            success: function () {
                toastr.success('Employee Sickness Updated Successfully');
            },
            error: function (err) {
                toastr.error(err);
            }
        });
    }
</script>

Murray.OnlineStaffManager.Web/Views/EmployeeSickness/Index.cshtml
@model Murray.OnlineStaffManager.Web.Models.ViewModels.EmployeeSicknessListViewModel
@{
    ViewBag.Title = "Employee Sickness";
    @Scripts.Render("~/bundles/auth", "~/bundles/utils")
}
<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#current">Current</a></li>
    <li><a data-toggle="tab" href="#historic">Historic</a></li>
    <li><a data-toggle="tab" href="#sicknessTypes">Sickness Management</a></li>
</ul>
<div class="tab-content">
    <div id="current" class="tab-pane fade in active">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="page-header text-primary">Employees Currently Sick</h3>
            </div>
        </div>
        @using (var table = Html.Bootstrap().Table().SetStyle(TableStyle.Bordered | TableStyle.Striped).SetResponsive().Begin())
        {
            @table.TableHeaderRow("Name", "Start of Sickness", "End of Sickness", "Actions")
            foreach (var employeeSickness in Model.Current)
            {
                using (var row = @table.TableDataRow().SetId(employeeSickness.Id.ToString()).Begin())
                {
                    @row.TableData(employeeSickness.Forename + " " + employeeSickness.Surname)
                    @row.TableData(employeeSickness.SicknessStartDate.ToString("dd/M/yyyy"))
                    if (employeeSickness.SicknessEndDate == null)
                    {
                        @row.TableData("-")
                    }
                    else
                    {
                        @row.TableData(employeeSickness.SicknessEndDate.Value.ToString("dd/M/yyyy"))
                    }

                    using (var tableData = row.TableData().Begin())
                    {
                        <div class="btn-group-sm">
                            @Html.Bootstrap().LinkButton("More", "Edit", "EmployeeSickness",
                      new
                      {
                          EmployeeSicknessId = employeeSickness.Id
                      }).SetState(ButtonState.Info).SetSize(ButtonSize.Sm).SetIcon(Icon.Edit)
                            <a href="#myModal" class="btn btn-danger open-delete-employee-sickness" data-toggle="modal" data-employee-sickness-id="@employeeSickness.Id"><i class="fa fa-trash-o"> </i> Delete</a>
                        </div>
                    }
                }
            }
        }

        <div class="row">
            <div class="col-xs-12">
                <a href="~/EmployeeSickness/Add" class="btn btn-lg btn-success pull-right"><i class="fa fa-thermometer-empty" aria-hidden="true"></i> New Sickness</a>
            </div>
        </div>
    </div>
    <div id="historic" class="tab-pane fade">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="page-header text-primary">Historic Employee Sicknesses</h3>
            </div>
        </div>
        @using (var table = Html.Bootstrap().Table().SetStyle(TableStyle.Bordered | TableStyle.Striped).SetResponsive().Begin())
        {
            @table.TableHeaderRow("Name", "Start of Sickness", "End of Sickness", "Actions")
            foreach (var employeeSickness in Model.Historic)
            {
                using (var row = @table.TableDataRow().SetId(employeeSickness.Id.ToString()).Begin())
                {
                    @row.TableData(employeeSickness.Forename + " " + employeeSickness.Surname)
                    @row.TableData(employeeSickness.SicknessStartDate.ToString("dd/M/yyyy"))
                    if (employeeSickness.SicknessEndDate == null)
                    {
                        @row.TableData("-")
                    }
                    else
                    {
                        @row.TableData(employeeSickness.SicknessEndDate.Value.ToString("dd/M/yyyy"))
                    }

                    using (var tableData = row.TableData().Begin())
                    {
                        <div class="btn-group-sm">
                            @Html.Bootstrap().LinkButton("More", "Edit", "EmployeeSickness",
                      new
                      {
                          EmployeeSicknessId = employeeSickness.Id
                      }).SetState(ButtonState.Info).SetSize(ButtonSize.Sm).SetIcon(Icon.Edit)
                            <a href="#myModal" class="btn btn-danger open-delete-employee-sickness" data-toggle="modal" data-employee-sickness-id="@employeeSickness.Id"><i class="fa fa-trash-o"> </i> Delete</a>
                        </div>
                    }
                }
            }
        }
    </div>
    <div id="sicknessTypes" class="tab-pane fade">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="page-header text-primary">System Sickness Types</h3>
            </div>
        </div>
        @Html.Action("List", "SicknessType")
        <div class="row">
            <div class="col-xs-12">
                <a href="~/EmployeeSickness/NewSicknessType" class="btn btn-lg btn-success pull-right"><i class="fa fa-thermometer-empty" aria-hidden="true"></i> New Sickness Type</a>
            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Confirmation</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" name="employeeSicknessId" id="employeeSicknessId" />
                <p>Are you sure you want to remove this employee sickness from the system? Click the close button to cancel.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal" onclick="deleteEmployeeSickness();"><i class="fa fa-trash-o"></i> Delete</button>
                <button class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).on("click", ".open-delete-employee-sickness", function () {
        // Get employeeId from the data-attr
        var employeeSickness = $(this).data('employee-sickness-id');
        // Set hidden field in modal to retrieve later
        $('.modal-body #employeeSicknessId').val(employeeSickness);
    });

    function deleteEmployeeSickness() {
        var apiBase = getApiBase() + "api/";
        // Get id of the employee that was clicked on
        var employeeSicknessId = $(".modal-body #employeeSicknessId").val();

        var entity = {
            "Id": employeeSicknessId
        };
        if (employeeSicknessId.length > 0) {
            $.ajax({
                url: apiBase + "Sickness/Delete",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(entity),
                headers:getTokenWithHeader(),
                type: "DELETE",
                success: function () {
                    // Find the employee in table and remove them from the DOM.
                    $('#' + employeeSicknessId).remove();
                    toastr.success('Employee Sickness Removed Successfully');
                },
                error: function () {
                    toastr.error("Employee Sickness with Id: " + employeeSicknessId + " could not be removed.");
                }
            });
        }
        else {
            toastr.error("Employee Sickness with Id: " + employeeSicknessId + " could not be removed.");
        }
    }
</script>

Murray.OnlineStaffManager.Web/Views/EmployeeSickness/NewSicknessType.cshtml
@model Murray.OnlineStaffManager.Web.Models.ViewModels.SicknessTypeAddViewModel
@{
    ViewBag.Title = "New Sickness Type";
}
@using (Html.BeginForm("AddNewSicknessType", "EmployeeSickness", FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="well">
        <p>Add a new sickness type to the system by using the form below.</p>
    </div>
    <hr />
    <div class="form-horizontal well">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group-lg">
            @Html.LabelFor(m => m.Description, new { @class = "control-label" })
            @Html.TextBoxFor(m => m.Description, new { @class ="form-control" })
            @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
        </div>
        <div class="form-group-lg">
            <br />
            <button type="submit" class="btn btn-lg btn-success"><i class="fa fa-thermometer"></i> Add</button>
        </div>
    </div>
}